const terms = [
    "wages",
    "tills",
    "travel agent",
    "groceries",
    "inventory",
    "advertising",
    "bedside",
    "capacity",
    "entertainment",
    "mainframe",
    "minicomputer",
    "PC",
    "laptop",
    "notebook",
    "handheld",
    "palmtop",
    "expansion cards",
    "memory chips",
    "power supply",
    "hard disk drive",
    "motherboard",
    "speaker",
    "serial ports",
    "COM1",
    "parallel port",
    "minus",
    "comma",
    "dot",
    "semicolon",
    "colon",
    "question mark",
    "exclamation mark",
    "three dot",
    "tilde",
    "underscore",
    "@",
    "forward slash",
    "axles",
    "rolling ball",
    "mousemat",
    "dash",
    "peripherals",
    "hub",
    "software",
    "hardware",
    "CPU",
    "network topologies",
    "hang",
    "router",
    "ISP",
    "internet service provider",
    "military",
    "3 winged craft",
    "alien ship",
    "was heading",
    "crashed",
    "coastguard",
    "commercial organization",
    "not-for-profit",
    "austria",
    "trackerball",
    "barcode reader",
    "scanner",
    "printer",
    "speech recognition board",
    "lightpen",
    "reflected light",
    "optical character recognising",
    "maximum resolution",
    "refresh rate",
    "aperture grill pitch",
    "adjust",
    "footrest",
    "copyholder",
    "magnet",
    "magnetic tape",
    "fingerprint",
    "dust",
    "smoke particle",
    "therefore",
    "represent",
    "modem",
    "recycle bin",
    "folder",
    "crosshair",
    "not available",
    "drag and drop arrow",
    "arrow pointer",
    "poiting finger",
    "hourglass",
    "dropdown listbox",
    "command button",
    "title bar",
    "advanced",
    "magnifying glass",
    "refer to",
    "secondary",
    "consist of",
    "are attached",
    "gigantic",
    "computer term",
    "machines",
    "flight",
    "disk",
    "drive",
    "device",
    "data",
    "speed",
    "monitor",
    "processor",
    "floppy disk",
    "alternate",
    "escape",
    "numeric keypad",
    "graphic tablet",
    "joystick",
    "microphone",
    "touchscreen",
    "digital camera",
    "lamp",
    "inkjet printer",
    "dye sublimation printer",
    "mono laser printer",
    "dot matrix printer",
    "fixed hard disk",
    "CD-ROM disk",
    "sounds",
    "fonts",
    "date and time",
    "volume",
    "drawing program",
    "network",
    "checkbox",
    "text box",
    "tab",
    "window",
    "icon",
    "pointer",
    "menu",
    "active window",
    "interface",
    "server",
    "client",
]

const descriptions = [
    "Compensation for work, often paid per hour.",
    "Automated checkout points in stores for transactions.",
    "Professional organizing and arranging trips.",
    "Food and household items in a grocery store.",
    "Detailed list of available stock or goods.",
    "Activities promoting products or services.",
    "Pertaining to the area next to a bed.",
    "The maximum amount something can hold or produce.",
    "Amusement or enjoyment.",
    "Large and powerful central computer.",
    "Smaller than a mainframe, larger than a microcomputer.",
    "Individual user computer.",
    "Portable and compact computer.",
    "Compact, lightweight laptop.",
    "Small, portable electronic device.",
    "Small computer designed to fit in the palm of a hand.",
    "Additional circuit boards for computer enhancement.",
    "Electronic components storing data.",
    "Device providing electrical energy to a computer.",
    "Data storage device inside a computer.",
    "Main circuit board in a computer.",
    "Device producing sound output.",
    "Connection points for serial communication.",
    "A specific serial communication port on a computer.",
    "Connection interface for parallel communication.",
    "Mathematical subtraction symbol.",
    "Punctuation mark indicating a pause in a sentence.",
    "A small, round mark or symbol.",
    "Punctuation mark indicating a stronger pause than a comma.",
    "Punctuation mark indicating a list or explanation.",
    "Punctuation mark indicating a question.",
    "Punctuation mark indicating strong emotion or emphasis.",
    "Ellipsis, indicating an omission or a pause.",
    "Punctuation mark with various uses, including diacritical.",
    "Symbol (_) used to underline or emphasize.",
    "Symbol used in email addresses.",
    "The "/" symbol used in paths or fractions.",
    "Rods connecting wheels in a vehicle.",
    "Mechanism in some computer mice.",
    "Surface for a computer mouse to move on.",
    "Punctuation mark indicating a break or emphasis.",
    "Additional devices connected to a computer.",
    "Device connecting multiple peripherals to a computer.",
    "Programs and applications for a computer.",
    "Physical components of a computer system.",
    "Core component performing calculations.",
    "Different arrangements of computer networks.",
    "A state of unresponsiveness in a program or system.",
    "Device directing data traffic on a network.",
    "Company providing internet access.",
    "Global network connecting computers worldwide.",
    "Relating to the armed forces or defense.",
    "Aircraft with three wings.",
    "Extraterrestrial spacecraft.",
    "Past tense of moving in a particular direction.",
    "Sudden and violent failure, often in a computer system.",
    "Maritime security and rescue organization.",
    "Business entity engaged in commerce.",
    "Organization focused on a mission rather than profit.",
    "European country.",
    "Input device with a rolling ball for navigation.",
    "Device scanning barcodes for data retrieval.",
    "Device capturing images or text for digital use.",
    "Device producing hard copies of digital content.",
    "Hardware for converting speech to text.",
    "Input device resembling a pen, used with a display.",
    "Light bouncing off a surface.",
    "Technology for converting printed text into digital characters.",
    "The highest level of detail in an image.",
    "Frequency of updating a display per second.",
    "Measurement of the distance between openings in a display.",
    "Modify or change settings.",
    "Support for feet to enhance comfort.",
    "Device holding documents for easy reading or typing.",
    "Object with magnetic properties.",
    "Storage medium using magnetic recording.",
    "Unique pattern on the fingertip used for identification.",
    "Fine particles floating in the air.",
    "Small particle released during combustion.",
    "Consequently or for that reason.",
    "To symbolize or stand for something.",
    "Device enabling computer communication over a network.",
    "Location for discarded digital files before permanent deletion.",
    "Digital container for organizing files.",
    "Reticle or target symbol on a display.",
    "Unreachable or inaccessible.",
    "Symbol indicating the ability to move items by dragging.",
    "Cursor in the shape of an arrow.",
    "Cursor resembling a hand pointing.",
    "Symbol indicating a process or waiting period.",
    "User interface element for selecting options from a list.",
    "Interface button triggering an action.",
    "Uppermost part of a window displaying its name.",
    "Highly developed or complex.",
    "Symbol or tool for zooming in on content.",
    "Direct attention or mention.",
    "Subordinate or less important.",
    "Comprised or made up of.",
    "Connected or linked.",
    "Extremely large or massive.",
    "A word or phrase related to computing.",
    "Mechanical devices or equipment.",
    "The act or process of flying.",
    "Storage medium often in the form of a flat, circular plate.",
    "Device for reading or writing data.",
    "Any piece of hardware used for a specific purpose.",
    "Information, especially in digital form.",
    "Rate at which something moves or operates.",
    "Display screen for computer output.",
    "Central component handling calculations.",
    "Portable storage medium with flexible magnetic disk.",
    "Another option or choice.",
    "Key on a keyboard used to interrupt or cancel.",
    "Section on a keyboard with numbers and arithmetic functions.",
    "Input device for drawing or writing on a digital surface.",
    "Input device for controlling movements.",
    "Device for capturing sound.",
    "Display screen with touch-sensitive capabilities.",
    "Device for capturing and storing digital images.",
    "Light source, often for workspace illumination.",
    "Printer using liquid ink for producing images.",
    "Printer using heat to transfer dye onto materials.",
    "Monochrome printer using laser technology.",
    "Printer creating images with dots.",
    "Non-removable data storage device.",
    "Compact Disc-Read Only Memory for data storage.",
    "Auditory sensations or vibrations.",
    "Different styles and sizes of text characters.",
    "Information indicating the calendar date and current time.",
    "Loudness or quantity of sound.",
    "Software for creating visual art or diagrams.",
    "Interconnected computers sharing resources and information.",
    "UI element for toggling options on or off.",
    "Area for entering and displaying text.",
    "User interface element for navigation or organization.",
    "Graphical interface displaying content on a computer screen.",
    "Graphic symbol representing a program or file.",
    "On-screen indicator controlled by a mouse or touchpad.",
    "List of options for a user to choose from.",
    "Currently focused or in-use interface window.",
    "Point of interaction between a user and a computer system.",
    "Computer providing resources or services to other computers.",
    "Computer or software using services provided by a server.",
]

let index = 0
updateUI()

function updateUI() {
    document.getElementById("description").innerText = descriptions[index]
    document.getElementById("term").innerText = terms[index]
    document.getElementById("input").focus()
}

function handleGetRandom() {
    index = Math.floor(Math.random() * terms.length)
    updateUI()
}

function handleGetOrder() {
    if (index < terms.length - 1) {
        index++
    } else {
        index = 0
    }
    updateUI()
}

function checkAnswer(index, input) {
    return input == terms[index]
}

function handleSubmit() {
    if (document.getElementById("input").value == terms[index]) {
        alert("Đúng")
    } else {
        alert("Sai")
    }

    document.getElementById("input").focus()
}

function handleDisplayTerm() {
    const termElement = document.getElementById("term")

    if (termElement.style.visibility == "visible") {
        termElement.style.visibility = "hidden"
    } else {
        termElement.style.visibility = "visible"
    }

    document.getElementById("input").focus()
}